---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ nethermind_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ nethermind_service_path }}'
    state:       '{{ compose_state }}'
    recreate:    '{{ compose_recreate }}'
    pull:        '{{ compose_pull }}'
